//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWork1EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Автобусные_маршрутыEntities : DbContext
    {
        public Автобусные_маршрутыEntities()
            : base("name=Автобусные_маршрутыEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Автобусы> Автобусы { get; set; }
        public virtual DbSet<Дни_движения> Дни_движения { get; set; }
        public virtual DbSet<Маршруты> Маршруты { get; set; }
        public virtual DbSet<Пункт_назначения> Пункт_назначения { get; set; }
        public virtual DbSet<Промежуточные_пункты> Промежуточные_пункты { get; set; }
        public virtual DbSet<Рейсы> Рейсы { get; set; }
    }
}
