//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWork1EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int id { get; set; }
        public string point { get; set; }
        public string days { get; set; }
        public int time { get; set; }
        public int idPoint { get; set; }
        public int idDay { get; set; }
    }
}
