//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWork1EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автобусы
    {
        public int Код_автобуса { get; set; }
        public string Марка { get; set; }
        public string ФИО_водителя { get; set; }
        public int Количество_мест { get; set; }
    }
}
