//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWork1EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        public int Код_маршрута { get; set; }
        public string Пункт_назначения { get; set; }
        public string Дни_движения { get; set; }
        public System.TimeSpan Время_в_пути { get; set; }
        public int Код_пункта { get; set; }
        public int Код_дня { get; set; }
    }
}
