//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWork1EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункт_назначения
    {
        public int Код_пункта { get; set; }
        public string Пункт_назначения1 { get; set; }
        public string Маршрут { get; set; }
    }
}
